
postgres:
  host: localhost
  port: 5432
  dbname: donnee_meteo
  user: postgres           
  password: 12345
  sslmode: prefer

api:
  weather:
    base_url: https://api.open-meteo.com/v1/forecast
    params:
      latitude: 48.8566
      longitude: 2.3522
      hourly: temperature_2m,relativehumidity_2m,windspeed_10m,pressure_msl
      timezone: Europe/Paris


paths:
  tmp_dir: /tmp/energitic_pipeline
  csv_input_dir: ./data/
  logs_dir: ./logs


pipeline:
  lookback_minutes: 1440 # 24 hours